#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
PLUGIN="$(basename $0)"
DOMAIN="$1"
EMAIL="$2"

PLUGIN_PATH="$SCRIPTPATH/plugins/$PLUGIN"
PLUGIN_AUTH_PATH="$SCRIPTPATH/plugins/$PLUGIN/auth"
PLUGIN_CLEANUP_PATH="$SCRIPTPATH/plugins/$PLUGIN/cleanup"

if [ "$PLUGIN" = "getcert" ]; then
    echo "You cannot use 'getcert' directly, use one of the supported plugins"
    exit 0
elif [ ! -d "$PLUGIN_PATH" ]; then
    echo "There is no Plugin '$PLUGIN'"
    exit 0
fi

if [ ! -f "$PLUGIN_AUTH_PATH" ]; then
    echo "The auth script for Plugin '$PLUGIN' is missing"
    exit 0
fi

if [ ! -f "$PLUGIN_CLEANUP_PATH" ]; then
    echo "The cleanup script for Plugin '$PLUGIN' is missing"
    exit 0
fi

if [ "$DOMAIN" = "" ]; then
    echo "Usage: $PLUGIN DOMAIN EMAIL"
    exit 0
fi


certbot certonly -n --manual-public-ip-logging-ok --agree-tos --email $EMAIL --manual --preferred-challenges=dns --manual-auth-hook $PLUGIN_AUTH_PATH --manual-cleanup-hook $PLUGIN_CLEANUP_PATH -d $DOMAIN
