#!/bin/bash

PLUGIN="$(basename $0)"
DOMAIN="$1"

if [ "$PLUGIN" = "getcert" ]; then
    echo "You cannot use 'getcert' directly, use one of the supported plugins"
    exit 0
elif [ ! -d "plugins/$PLUGIN" ]; then
    echo "There is no Plugin '$PLUGIN'"
    exit 0
fi

if [ ! -f "plugins/$PLUGIN/auth" ]; then
    echo "The auth script for Plugin '$PLUGIN' is missing"
    exit 0
fi

if [ ! -f "plugins/$PLUGIN/cleanup" ]; then
    echo "The cleanup script for Plugin '$PLUGIN' is missing"
    exit 0
fi

if [ "$DOMAIN" = "" ]; then
    echo "Usage: $PLUGIN DOMAIN"
    exit 0
fi


certbot certonly -n --manual-public-ip-logging-ok --manual --preferred-challenges=dns --manual-auth-hook plugins/$PLUGIN/auth --manual-cleanup-hook plugins/$PLUGIN/cleanup -d $DOMAIN
