#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
PLUGIN="$(basename ${0/-renew})"
DOMAIN="$1"

PLUGIN_PATH="$SCRIPTPATH/plugins/$PLUGIN"
PLUGIN_AUTH_PATH="$SCRIPTPATH/plugins/$PLUGIN/auth"
PLUGIN_CLEANUP_PATH="$SCRIPTPATH/plugins/$PLUGIN/cleanup"

if [ "$PLUGIN" = "renewcert" ]; then
    echo "You cannot use 'renewcert' directly, use one of the supported plugins"
    exit 0
elif [ ! -d "$PLUGIN_PATH=" ]; then
    echo "There is no Plugin '$PLUGIN'"
    exit 0
fi

if [ ! -f "$PLUGIN_AUTH_PATH" ]; then
    echo "The auth script for Plugin '$PLUGIN' is missing"
    exit 0
fi

if [ ! -f "$PLUGIN_CLEANUP_PATH" ]; then
    echo "The cleanup script for Plugin '$PLUGIN' is missing"
    exit 0
fi

if [ "$DOMAIN" = "" ]; then
    echo "Usage: $PLUGIN DOMAIN"
    exit 0
fi


certbot renew -n --cert-name $DOMAIN --manual --preferred-challenges=dns --manual-auth-hook $PLUGIN_AUTH_PATH --manual-cleanup-hook $PLUGIN_CLEANUP_PATH
