#!/usr/bin/php
<?php

require "helpers";

try {
    //* Login to the remote server
    if($session_id = $client->login($username, $password)) {
        msg('Logged into remote server sucessfully. The SessionID is '.$session_id);
        $domain_array = explode('.', $certbot_domain);
        $domain_reverted_array = new ArrayIterator(array_reverse($domain_array));
        foreach ($domain_reverted_array as $domain_part) {
            $domain_only = $domain_part . "." . $domain_only;
            msg("Trying to find domain with origin: ".$domain_only);
            $zone = $client->dns_zone_get($session_id, array('origin' => $domain_only));
            $errors = array_filter($zone);

            if (!empty($zone)) { break; } else { msg($domain_only." Does not exist. Continuing..."); }
	}

        if (empty($zone)) {
            exit(1);
	}

        msg("Trying to find :".implode('.', $domain_array));
        $dns_entry = $client->dns_txt_get($session_id, array('name' => "_acme-challenge.".$certbot_domain."."));
        if ($dns_entry[0]) {
            msg("Entry does exist, lets delete it.");
            $dns_entry = $client->dns_txt_delete($session_id, $dns_entry[0]['id']);
        } else {
            msg("Entry _acme-challenge.$certbot_domain does not exist. Nothing to delete.");
            exit(0);
        }
        $zone = $client->dns_zone_get($session_id, array('origin' => $zone[0]['origin']));
        $zone[0]['serial'] = $zone[0]['serial'] + 1;
        $updated_zone = $client->dns_zone_update($session_id, 0, $zone[0]['id'], $zone[0]);

        //* Logout
        if($client->logout($session_id)) {
                msg("Logout done");
        }

    }
} catch (SoapFault $e) {
        msg('SOAP Error: '.$e->getMessage());
        die("Please contact the server administator\n");
}


?>
