#!/bin/bash
# create dns entry via rndc
#
#        $dns_entry = $client->dns_txt_get($session_id, array('name' => "_acme-challenge.".$certbot_domain."."));
#                "name" => "_acme-challenge.".$certbot_domain.".",
#                "type" => "TXT",
#                "data" => $certbot_validation,
#                "ttl" => 60,
#                "active" => "Y"
#            );
#            msg("Adding following $certbot_validation to Entry: ".print_r($dns_entry, true));
#
PLUGIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ ! -f $PLUGIN_DIR/config ]; then
    echo "No config file detected. Aborting."
    exit 1
fi

. $PLUGIN_DIR/config

CURRENT_DOMAIN="$(echo $CERTBOT_DOMAIN | perl -lne 'print $1 if (m(([^.]+\.[^.]+$)))')"

nsupdate -v -y $RNDC_KEY:$RNDC_SECRET << EOF
server $RNDC_HOST
zone $CURRENT_DOMAIN
update delete _acme-challenge.$CERTBOT_DOMAIN
update add _acme-challenge.$CERTBOT_DOMAIN 60 IN TXT "$CERTBOT_VALIDATION"
show
send
EOF

sleep $WAIT_SECONDS
