#!/bin/bash

if [ "$DEPLOY_SERVICES" != "" ]; then
    echo "$DEPLOY_SERVICES" | sed -e 's/,/\n/g' | while read service; do
        ( ( systemctl status $service >/dev/null 2>&1 && systemctl reload $service ) || ( service $service status >/dev/null 2>&1 && service $service reload ) ) || echo "$service could not be reloaded"
    done
fi
